blank_issues_enabled: false
contact_links:
  - name: Discord support
    url: https://discord.gg/myftb
    about: For quick questions and community help, join our Discord server.
  - name: MyFTB website
    url: https://myftb.de
    about: Visit our website for news and announcements.
